spring:
  application:
    name: Matna
#  security:
#    user:
#      name: admin
#      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://43.201.44.107:3306/mydb
    username: mydbid
    password: mydbpw

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 5432

file:
  upload:
    path: uploads